---
- hosts: "{{ service_name }}--db:{{ service_name }}--lb:{{ service_name }}--web"
- hosts: "{{ service_name }}--app"
  vars:
    db_ipv4: "{{hostvars[groups[service_name + '--db'][0]].ansible_default_ipv4.address}}"
    ansible_become: false
    join_domain: true
    sysprep_host: false
    windows_domain_info:
      dns_server: "{{ windnsaddr }}"
      dns_domain_name: "{{ windomianname }}"
      domain_admin_user: "{{ windomainadminuser }}"
      domain_admin_password: "{{ windomainadminpass }}"
  roles:
    - role: ansible-windows-domain-member
  tasks:
    - name: add db ip host entry
      win_lineinfile:
        path: C:\windows\system32\drivers\etc\hosts
        regexp: "db.{{ app_domain }}"
        line: "{{ db_ipv4 }} db.{{ app_domain }}"
    - name: install IIS
      win_feature:
        name: Web-Server
        state: present
        include_sub_features: true
        include_management_tools: true
    - name: check for downloaded deployer
      win_stat:
        path: C:\WebDeploy_2_10_amd64_en-US.msi
      register: webdeploy_stat
    - name: download web deploy installer
      win_get_url:
        #url: http://download.microsoft.com/download/8/9/B/89B754A5-56F7-45BD-B074-8974FD2039AF/WebDeploy_2_10_amd64_en-US.msi
        url: http://f46882043020c0baa0d7-f449ff5052d0024add9c90d2e2df950e.r86.cf2.rackcdn.com/WebDeploy_2_10_amd64_en-US.msi
        timeout: 1000
        dest: C:\
        force: false
      when: webdeploy_stat.stat.exists == false
    - name: Install web deploy
      win_command: msiexec /I C:\WebDeploy_2_10_amd64_en-US.msi /quiet ADDLOCAL=ALL
    - name: push webapp code
      win_copy:
        src: content/middleware
        dest: C:\
    - name: Ensure webroot directory
      win_file:
        path: C:\inetpub\windowsdemoapp
        state: directory
    - name: Setup app pool
      win_iis_webapppool:
        name: "{{ app_domain }}"
        state: started
        attributes:
          autoStart: true
          enable32BitAppOnWin64: true
    - name: Setup website
      win_iis_website:
        name: windowsdemo.com
        state: started
        port: 80
        ip: '*'
        hostname: "app.{{ app_domain }}"
        application_pool: "{{ app_domain }}"
        physical_path: C:\inetpub\windowsdemoapp
    - name: Create registry directory
      win_regedit:
        path: HKLM:\SOFTWARE\WindowsDemo
    - name: Create dbname registry entry
      win_regedit:
        path: HKLM:\SOFTWARE\WindowsDemo
        name: dbname
        data: "{{ dbname }}"
    - name: Create dburl registry entry
      win_regedit:
        path: HKLM:\SOFTWARE\WindowsDemo
        name: dburl
        data: "db.{{ app_domain }}"
    - name: Create dbuser registry entry
      win_regedit:
        path: HKLM:\SOFTWARE\WindowsDemo
        name: dbuser
        data: "{{ dbusername }}"
    - name: Create dbpass registry entry
      win_regedit:
        path: HKLM:\SOFTWARE\WindowsDemo
        name: dbpass
        data: "{{ dbpassword }}"
      register: registry_dbpass
    - name: Deploy application
      win_command: winapp1.deploy.cmd /Y
      args:
        chdir: C:\middleware
- hosts: "{{ service_name }}--db"
  vars:
    mysql_enabled_on_startup: true
    overwrite_global_mycnf: true
    mysql_databases:
      - name: "{{ dbname }}"
    mysql_users:
      - name: "{{ dbusername }}"
        password: "{{ dbpassword }}"
        host: '%'
        priv: "{{ dbname }}.*:ALL"
  roles:
    - role: rhnregister
    - role: mysql
  tasks:
    - name: Copy database base sql file
      copy:
        src: content/database/windowsdemo.sql
        dest: /tmp
    - name: Ensure database exists
      mysql_db:
        name: windowsdemo
        state: present
    - name: Test for table existence
      stat:
        path: /var/lib/mysql/windowsdemo/names.ibd
      register: db_table
    - name: import database data
      mysql_db:
        name: windowsdemo
        state: import
        target: /tmp/windowsdemo.sql
      when: db_table.stat.exists == false
    - name: Check if iptables is running
      command: service iptables status
      args:
        warn: false
      ignore_errors: yes
      register: iptables_status
      failed_when: true == false
    - name: Ensure Port 3306 open
      iptables:
        chain: IN_public_allow
        destination_port: 3306
        protocol: tcp
        match: tcp
        ctstate: NEW
        jump: ACCEPT
      when: iptables_status.rc == 0
    - name: Save iptables rules
      command: service iptables save
      args:
        warn: false
      when: iptables_status.rc == 0
- hosts: "{{ service_name }}--web"
  vars:
    app_ips: "{{ groups[service_name + '--app'] | map('extract', hostvars, ['ansible_ssh_host']) | join('\", \"') }}"
    php_enable_php_fpm: false
    php_webserver_daemon: "nginx"
    php_fpm_listen: "127.0.0.1:9000"
    php_fpm_pm_max_children: 50
    php_fpm_pm_start_servers: 5
    php_fpm_pm_min_spare_servers: 5
    php_fpm_pm_max_spare_servers: 5
    php_opcache_enable: "0"
    php_opcache_enable_cli: "0"
    nginx_vhosts:
      - listen: "80"
        nginx_remove_default_vhost: true
        server_name: "www.{{ app_domain }}"
        root: "/var/www/{{ app_domain }}"
        index: "index.php index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "{{ app_domain }}.conf"
        extra_parameters: |
          location ~ \.php$ {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass 127.0.0.1:9000;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }
  roles:
    - role: rhnregister
    - role: nginx
    - role: php
  tasks:
    - name: debug vars
      debug:
        var: app_ips
    - name: Check if iptables is running
      command: service iptables status
      args:
        warn: false
      ignore_errors: yes
      register: iptables_status
      failed_when: true == false
    - name: Ensure Port 80 open
      iptables:
        chain: IN_public_allow
        destination_port: 80
        protocol: tcp
        match: tcp
        ctstate: NEW
        jump: ACCEPT
      when: iptables_status.rc == 0
    - name: Save iptables rules
      command: service iptables save
      args:
        warn: false
      when: iptables_status.rc == 0
    - name: Ensure php-fpm service running
      service:
        name: php54-php-fpm
        state: started
    - name: Manually enable php-fpm service
      command: systemctl enable php54-php-fpm
      args:
        warn: false
    - name: Remove stock nginx domain
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
    - name: Ensure nginx service running
      service:
        name: nginx
        state: reloaded
    - name: Ensure webroot directory
      file:
        path: "/var/www/{{ app_domain }}"
        state: directory
    - name: Copy front end code
      copy:
        src: content/frontend/web/
        dest: "/var/www/{{ app_domain }}"
    - name: Write config template
      template:
        src: content/frontend/_config.php.j2
        dest: "/var/www/{{ app_domain }}/_config.php"
- hosts: "{{ service_name }}--lb"
  vars:
    backend_group: "{{ service_name }}--web"
  roles:
    - role: rhnregister
    - role: haproxy
#- hosts: lbInt
#  vars:
#    backend_group: app
#  roles:
#    - role: rhnregister
#    - role: haproxy
